yarnPath: .yarn/releases/yarn-2.4.0.cjs

pnpMode: loose

packageExtensions:
    "debug@*":
        dependencies:
            supports-color: "^7.1.0"
    "promise-inflight@*":
        dependencies:
            bluebird: "^3.7.2"
    "@storybook/components@*":
        dependencies:
            regenerator-runtime: ">=0.11.1"
