yarnPath: .yarn/releases/yarn-2.4.0.cjs

pnpMode: loose
nodeLinker: pnp

packageExtensions:
    "debug@*":
        dependencies:
            supports-color: "^7.1.0"
    "promise-inflight@*":
        dependencies:
            bluebird: "^3.7.2"
    "@storybook/components@*":
        dependencies:
            regenerator-runtime: ">=0.11.1"
    "@types/react@*":
        dependencies:
            prop-types: ">=0.1.0"
    "@types/node@*":
        dependencies:
            util: ">=0.4.9"
            os: ">=0.0.0"
            url: ">=0.4.9"
            querystring: ">=0.0.1"
            events: ">=0.1.0"
